### ISSUE TITLE
Continuously rebuilding?

### ISSUE THREAD

**Issue by maxvodo** [maxvodo/bitbucket-pullrequest-builder-plugin#9]
Check [this lines](https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/blob/6a9340ea2cf96f283e26b996b88d2c520401bd21/src/main/java/bitbucketpullrequestbuilder/bitbucketpullrequestbuilder/BitbucketRepository.java#L195), especially `buildKeyPart` variable.
BitBucket API has limited size of key part in API POST request.

Link to [#62](https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/issues/62) issue.

**Comment by kristofmeixner** [comment]
Maybe it makes sense to reference not the whole commit hash (which has 32 characters)  but the abbreviated one.

**Comment by maxvodo** [comment]
@Mercynary, @pdjtrifork, @tnguyen14
So, I think this release works as expected. On all my projects alpha version of plugin works fine. After updating plugin new pull requests may trigger one more build.
Can you update plugin to this developer release [bitbucket-pullrequest-builder 1.4.15](https://github.com/maxvodo/bitbucket-pullrequest-builder-plugin/releases/tag/bitbucket-pullrequest-builder-1.4.15) and check it out?

**Comment by tnguyen14** [comment]
@maxvodo I installed it, but it seems like the job is not picking up the build automatically anymore? (I had to disable the job on version `1.4.13`, and reenabled it when I install `1.4.15`). Neither a `test this please` comment or a change to the PR triggered the build.

**Comment by maxvodo** [comment]
@tnguyen14, thx for response. Show me please your logs :smile:.

**Comment by maxvodo** [comment]
@Mercynary, @pdjtrifork, @tnguyen14: New [beta release](https://github.com/maxvodo/bitbucket-pullrequest-builder-plugin/releases/latest), fix #9, #10. Stay tuned.

**Comment by tnguyen14** [comment]
@maxvodo I see these errors in the log. Might be helpful

```
Feb 04, 2016 1:03:00 AM INFO bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder run
Build Start.
Feb 04, 2016 1:03:00 AM WARNING hudson.triggers.Trigger checkTriggers
bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run() failed for hudson.model.FreeStyleProject@6a7f81db[sitegenesis-pr]
java.lang.NullPointerException
    at com.cloudbees.plugins.credentials.matchers.IdMatcher.<init>(IdMatcher.java:49)
    at com.cloudbees.plugins.credentials.CredentialsMatchers.withId(CredentialsMatchers.java:112)
    at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getCredentials(BitbucketRepository.java:309)
    at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.init(BitbucketRepository.java:71)
    at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.init(BitbucketRepository.java:54)
    at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:36)
    at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:195)
    at hudson.triggers.Trigger.checkTriggers(Trigger.java:268)
    at hudson.triggers.Trigger$Cron.doRun(Trigger.java:217)
    at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by tnguyen14** [comment]
@maxvodo using your beta release version seems to be going ok. Will update if the rebuilding occurs again.

**Comment by tnguyen14** [comment]
@maxvodo any thought on when there will be an official release with your fix?

**Comment by maxvodo** [comment]
@tnguyen14, I think on this weekend @nishio-dens will release new version.

**Comment by kristofmeixner** [comment]
Works for me too.

**Comment by tnguyen14** [comment]
@maxvodo has the PR for this change been merged in @nishio-dens repo?

**Comment by maxvodo** [comment]
@tnguyen14: yep, all changes already merged in @nishio-dens master branch.
